[package]
name = "python_string_repl_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
python_string_repl = { path = "../python_string_repl" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "python_string_repl"
path = "src/main.rs"
