[package]
name = "python_string_repl"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22"
flate2 = "1.0"
regex = "1.10"
rustpython-parser = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
